// Code generated by entc, DO NOT EDIT.

package ent

import (
	"backend/ent/car"
	"backend/ent/plane"
	"backend/ent/schema"
	"backend/ent/schema/pulid"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	carMixin := schema.Car{}.Mixin()
	carMixinFields0 := carMixin[0].Fields()
	_ = carMixinFields0
	carMixinFields1 := carMixin[1].Fields()
	_ = carMixinFields1
	carFields := schema.Car{}.Fields()
	_ = carFields
	// carDescCreatedAt is the schema descriptor for createdAt field.
	carDescCreatedAt := carMixinFields1[0].Descriptor()
	// car.DefaultCreatedAt holds the default value on creation for the createdAt field.
	car.DefaultCreatedAt = carDescCreatedAt.Default.(func() time.Time)
	// carDescUpdatedAt is the schema descriptor for updatedAt field.
	carDescUpdatedAt := carMixinFields1[1].Descriptor()
	// car.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	car.DefaultUpdatedAt = carDescUpdatedAt.Default.(func() time.Time)
	// car.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	car.UpdateDefaultUpdatedAt = carDescUpdatedAt.UpdateDefault.(func() time.Time)
	// carDescID is the schema descriptor for id field.
	carDescID := carMixinFields0[0].Descriptor()
	// car.DefaultID holds the default value on creation for the id field.
	car.DefaultID = carDescID.Default.(func() pulid.ID)
	planeMixin := schema.Plane{}.Mixin()
	planeMixinFields0 := planeMixin[0].Fields()
	_ = planeMixinFields0
	planeMixinFields1 := planeMixin[1].Fields()
	_ = planeMixinFields1
	planeFields := schema.Plane{}.Fields()
	_ = planeFields
	// planeDescCreatedAt is the schema descriptor for createdAt field.
	planeDescCreatedAt := planeMixinFields1[0].Descriptor()
	// plane.DefaultCreatedAt holds the default value on creation for the createdAt field.
	plane.DefaultCreatedAt = planeDescCreatedAt.Default.(func() time.Time)
	// planeDescUpdatedAt is the schema descriptor for updatedAt field.
	planeDescUpdatedAt := planeMixinFields1[1].Descriptor()
	// plane.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	plane.DefaultUpdatedAt = planeDescUpdatedAt.Default.(func() time.Time)
	// plane.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	plane.UpdateDefaultUpdatedAt = planeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// planeDescID is the schema descriptor for id field.
	planeDescID := planeMixinFields0[0].Descriptor()
	// plane.DefaultID holds the default value on creation for the id field.
	plane.DefaultID = planeDescID.Default.(func() pulid.ID)
}
